#pragma once
#include <wx/app.h>
#include <wx/frame.h>
#include <wx/panel.h>
#include <wx/toolbar.h>
#include <wx/image.h>
#include <wx/menu.h>
#include <wx/timer.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statbmp.h>
#include <wx/filedlg.h>
#include <wx/gauge.h>
#include <wx/button.h>
#include <wx/config.h>
#include <wx/confbase.h>
#include <wx/fileconf.h>
#include <wx/filename.h>
#include <wx/settings.h>
#include <wx/msgdlg.h>
#include <wx/valgen.h>
#include <wx/snglinst.h>
#include <wx/stdpaths.h>
#include <wx/file.h>
#include <wx/filename.h>
#include <wx/progdlg.h>
#include <wx/dnd.h>
#include <wx/html/htmlwin.h>
#include <wx/log.h>
#include <wx/socket.h>
#include <wx/textctrl.h>
#include <wx/notebook.h>
#include <wx/fs_mem.h>
#include <wx/bitmap.h>
#include <wx/mstream.h>
#include <wx/clipbrd.h>
